import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";

const Layout = ({ children, title }) => {
  const [searchName, setSearchName] = useState("search");

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-slate-900 py-10 mb-10">
        <Link href="/">
          <h1 className="text-6xl text-center text-amber-400">{title}</h1>
        </Link>
        <div className="flex items-center justify-center mt-4">
          <input
            className="text-black"
            type={"text"}
            value={searchName}
            onChange={(e) => setSearchName(e.target.value)}
          />
          <Link href={`/pokemon/${searchName.toLocaleLowerCase()}`}>
            <button className="ml-4 bg-black rounded-lg w-[150px]">
              Search
            </button>
          </Link>
        </div>
      </header>

      <main className="container mx-auto">{children}</main>
    </div>
  );
};

export default Layout;
